
title: Simple Theme
author: GitHub User

setting:
  title: My Site
  tagline: It all about my site.
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  social_links:
      twitter: test
      github:  test
      rss: rss

baseurl: "/"

permalink: /posts/:title/



